account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    #path('login/',views.user_login,name='login'),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('register/',views.register,name='register'),
]

fisch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('',include('question.urls', namespace='question')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
]

question/urls.py
from django.urls import path
from . import views

app_name = 'question'

urlpatterns = [
    path('simple_question',views.simple_question,name='simple_question'),
    path('simple_test',views.simple_test,name='simple_test'),
    path('fischerschein_info',views.fischerschein_info,name='fischerschein_info'),
    path('FAQ',views.FAQ,name='FAQ'),
    path('project_info',views.project_info,name='project_info'),
    path('',views.main_page,name='main_page'),
]

question/models.py
from django.db import models

class Question(models.Model):
    
    MAIN_TOPIC_CHOICES_GER = (
        ('Fischkunde und -hege','Fischkunde und -hege'),
        ('Pflege der Fischgewässer','Pflege der Fischgewässer'),
        ('Fanggeräte und deren Gebrauch','Fanggeräte und deren Gebrauch'),
        ('Behandlung der gefangenen Fische','Behandlung der gefangenen Fische'),
        ('Einschlägige Rechtsvorschriften','Einschlägige Rechtsvorschriften'),
    )

    MAIN_TOPIC_CHOICES_PL = (
        ('budowa ryb','budowa ryb'),
        ('dbanie o miejsca połowu','dbanie o miejsca połowu'),
        ('sprzęt wędkarski i jego użycie','sprzęt wędkarski i jego użycie'),
        ('obchodzenie się ze złapaną rybą','obchodzenie się ze złapaną rybą'),
        ('odpowiadające przepisy','odpowiadające przepisy'),
    )

    UNDER_TOPIC_CHOICES_GER = (
        ('Aufbau des Fischkörpers, Bau und Funktion der Fischorgane','Aufbau des Fischkörpers, Bau und Funktion der Fischorgane'),
        ('Unterscheidung einheimischer Fischarten','Unterscheidung einheimischer Fischarten'),
        ('häufig auftretende Fischkrankheite','häufig auftretende Fischkrankheiten'),
        ('Notwendigkeit von Besatzmaßnahme','Notwendigkeit von Besatzmaßnahme'),
        ('Naturnahrung, Sauerstoff und Temperaturverhältnisse','Naturnahrung, Sauerstoff und Temperaturverhältnisse'),
        ('Sonstiges-Fischkunde und -hege','Sonstiges-Fischkunde und -hege'),
        ('Fischereiliche Gewässerkunde','Fischereiliche Gewässerkunde'),
        ('Schutz der Gewässer vor Verunreinigung','Schutz der Gewässer vor Verunreinigung'),
        ('Ufer und Gelegeschutz','Ufer und Gelegeschutz'),
        ('Mittel und Geräte zur Gewässerinstandhaltung','Mittel und Geräte zur Gewässerinstandhaltung'),
        ('Sonstiges-Pflege der Fischgewässer','Sonstiges-Pflege der Fischgewässer'),
        ('Fanggeräte und deren Gebrauch','Fanggeräte und deren Gebrauch'),
        ('Betäuben, Töten und Schlachten von Fischen','Betäuben, Töten und Schlachten von Fischen'),
        ('Aufbewahrung von Fischen','Aufbewahrung von Fischen'),
        ('Tierschutz','Tierschutz'),
        ('Fischereiordnung des Landes Brandenburg (BbgFischO','Fischereiordnung des Landes Brandenburg (BbgFischO)'),
        ('Sonstiges-Behandlung der gefangenen Fische','Sonstiges-Behandlung der gefangenen Fische'),
        ('Landesfischereirecht','Landesfischereirecht'),
        ('Tierschutzrecht','Tierschutzrecht'),
        ('Naturschutzrecht','Naturschutzrecht'),
        ('Wasserrecht','Wasserrecht'),
        ('Sonstiges-Einschlägige Rechtsvorschriften','Sonstiges-Einschlägige Rechtsvorschriften'),
    )

    UNDER_TOPIC_CHOICES_PL = (
        ('budowa organów u ryb','budowa organów u ryb'),
        ('rozróżnianie rodzinych ryb','rozróżnianie rodzinych ryb'),
        ('najczęstrze choroby u ryb','najczęstrze choroby u ryb'),
        ('zarybianie','zarybianie'),
        ('naturalne warunki życia, tlen i temperatura','naturalne warunki życia, tlen i temperatura'),
        ('pozostałe-budowa ryb','pozostałe-budowa ryb'),
        ('hydrologia','hydrologia'),
        ('ochrona wód przed zanieczyszczeniem','ochrona wód przed zanieczyszczeniem'),
        ('ochrona brzegów i łowisk','ochrona brzegów i łowisk'),
        ('środki i sprzęt do utrzynania łowisk w dobrym stanie','środki i sprzęt do utrzynania łowisk w dobrym stanie'),
        ('pozostałe-dbanie o miejsca połowu','pozostałe-dbanie o miejsca połowu'),
        ('sprzęt wędkarski i jego użycie','sprzęt wędkarski i jego użycie'),
        ('ogłuszanie, uśmiercanie i szlachtowanie ryb','ogłuszanie, uśmiercanie i szlachtowanie ryb'),
        ('przechowywanie ryb','przechowywanie ryb'),
        ('ochrona zwierząt','ochrona zwierząt'),
        ('prawo dot. wędkarstwa w Brandenburgii','prawo dot. wędkarstwa w Brandenburgii'),
        ('pozostałe-obchodzenie się ze złapaną rybą','pozostałe-obchodzenie się ze złapaną rybą'),
        ('prawo połowu','prawo połowu'),
        ('prawo dot. ochrony zwierząt','prawo dot. ochrony zwierząt'),
        ('prawo dot. ochrony przyrody','prawo dot. ochrony przyrody'),
        ('prawo wodne','prawo wodne'),
        ('pozostałe-odpowiadające przepisy','pozostałe-odpowiadające przepisy'),
    )

    question_id = models.IntegerField()

    main_topic_ger = models.CharField(max_length=200, choices=MAIN_TOPIC_CHOICES_GER)
    main_topic_pl = models.CharField(max_length=200, choices=MAIN_TOPIC_CHOICES_PL)

    under_topic_ger = models.CharField(max_length=200, choices=UNDER_TOPIC_CHOICES_GER)
    under_topic_pl = models.CharField(max_length=200, choices=UNDER_TOPIC_CHOICES_PL)

    question_ger = models.TextField(max_length=400)
    question_pl = models.TextField(max_length=400)

    answer_a_ger = models.TextField(max_length=400)
    answer_a_pl = models.TextField(max_length=400)

    answer_b_ger = models.TextField(max_length=400)
    answer_b_pl = models.TextField(max_length=400)

    answer_c_ger = models.TextField(max_length=400)
    answer_c_pl = models.TextField(max_length=400)

    correct_answer_ger = models.TextField(max_length=400)
    correct_answer_pl = models.TextField(max_length=400)

    objects = models.Manager()

    def __str__(self):
        return f'{self.question_id} . {self.question_ger}'
    
    class Meta:
        ordering = ('question_id',)

question/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question
from django.utils.translation import gettext as _

def simple_question(request):
    all_questions = Question.objects.all()
    return render(request,'question/simple_question.html',{'all_questions':all_questions})

def simple_test(request):
    all_questions = Question.objects.all()
    return render(request,'question/simple_test.html',{'all_questions':all_questions})

def main_page(request):
    return render(request,'question/main_page.html')

def fischerschein_info(request):
    return render(request,'question/fischerschein_info.html')

def FAQ(request):
    return render(request,'question/FAQ.html')

def project_info(request):
    return render(request,'question/project_info.html')

question/templates/question/FAQ.html
{% extends 'base.html' %}

{% block content %}
    <p>FAQ</p>
{% endblock %}

question/templates/question/fischerschein_info.html
{% extends 'base.html' %}

{% block content %}
    <p>Fischerschein info</p>
{% endblock %}

question/templates/question/main_page.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
    <div class='container-fluid'>
        <div class='row'>
            <div class='col text-center ml-4 mb-4 mt-4 mr-2 d-flex'>
                <div class='col-md-12 border p-3 account-bg'>
                    <h3>{% trans "ohne ein Konto zu erstellen" %}</h3>
                    <p><i class="fas fa-hand-point-right"></i> {% trans "Zeichnen Sie aus 600 offiziellen Testfragen, beantworten Sie und überprüfen Sie die Antwort" %}</p>
                    <p><i class="fas fa-hand-point-right"></i> {% trans "Zeichnen Sie den Test nach offiziellen Regeln - 60 Fragen, 12 Fragen aus jeder Testabteilung und überprüfen Sie das Ergebnis" %}</p>
                    <p><i class="fas fa-hand-point-right"></i> {% trans "Informationen über Fischereischein lesen" %}</p>
                    <a href='{% url "question:simple_question" %}' class='btn btn-secondary'><i class='far fa-comment'></i>  {% trans "einzelne Frage" %}</a>
                    <a href='{% url "question:simple_test" %}' class='btn btn-secondary'><i class='far fa-comments'></i> {% trans "vollständiger Test" %}</a>
                </div>
            </div>
            <div class='col text-center mr-4 mb-4 mt-4 ml-2 d-flex'>
                <div class='col-md-12 border p-3 account-bg'>
                    <h3>{% trans "Konto erstellen" %}</h3>
                    <p>* ..........</p>
                    <p>* ..........</p>
                    <p>* ..........</p>
                    <p>* ..........</p>
                    <p>* ..........</p>
                    <a href='{% url "account:register" %}' class='btn btn-secondary'><i class="fas fa-user-plus"></i> {% trans "Konto erstellen" %}</a>
                    <a href='{% url "account:login" %}' class='btn btn-secondary'><i class="fas fa-user-check"></i> {% trans "einloggen" %}</a>
                </div>
            </div>
        </div>
        <div class='row text-center'>
            <div class='col'>
                <span class='icon-benefit'>
                    <i class="fas fa-chart-line"></i>
                </span>
                <h4>{% trans "Überprüfen Sie den Fortschritt" %}</h4>
                <p>{% trans "Überprüfen Sie den Fortschritt nach Thema und im Laufe der Zeit" %}</p>
            </div>
            <div class='col'>
                <span class='icon-benefit'>
                    <i class="fas fa-walking"></i>
                </span>
                <h4>{% trans "flexibel" %}</h4>
                <p>{% trans "Lernen Sie durch Auswahl, Frage, Test oder Themenbereich" %}</p>
            </div>
            <div class='col'>
                <span class='icon-benefit'>
                    <i class="fas fa-mobile-alt"></i>
                </span>
                <h4>{% trans "zu jeder Zeit" %}</h4>
                <p>{% trans "Lernen Sie auf Ihrem Computer oder Smartphone" %}</p>
            </div>
        </div>
        <div class='row m-4 account-bg'>
            <div class='col-4 d-flex'>
                <img class='img-fluid rounded-circle align-self-center mx-auto my-img p-2' src='{% static "img/my-photo-square.jpg" %}'>
            </div>
            <div class='col-8 d-flex'>
                <div class='align-self-center mx-auto'>
                    <h4> {% trans "über das Projekt und mich" %}</h4>
                    <p>
                        {% trans "Derzeit suche ich ein bezahltes Praktikum oder arbeite auf Junior-Ebene in Berlin im Webbereich. Meine Lieblingssprachen sind Javascript und Python. Weitere Informationen finden Sie auf 'Über mich und das Projekt' Seite. Das Projekt wurde für ein Portfolio erstellt. Es wurde hauptsächlich in Python (Django) und Javascript sowie in HTML, CSS und Bootstrap durchgeführt. Es verwendet MySQl als Datenbank." %}
                    </p>
                </div>
            </div>
         </div>
    </div>
{% endblock %}

question/templates/question/project_info.html
{% extends 'base.html' %}

{% block content %}
    <p>Project info</p>
{% endblock %}

question/templates/question/simple_question.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class='text-center m-2 p-2 account-bg'>
        <h6 data-translate-flag='true'>aby uzyskać tłumaczenie na język polski najedź myszką na ikonę: <span class='flag-icon flag-icon-pl'></span> znajdującą się obok pytania lub odpowiedzi</h6>
        <button class='btn btn-secondary' type='button' id='draw-new-question-btn'><i class="far fa-file"></i> {% trans "eine Frage zeichnen" %}</button>
        <button class='btn btn-secondary' type='button' id='check-question-btn'><i class="fas fa-tasks"></i> {% trans "überprüfen" %}</button>
        <p>
            <span class="font-weight-bold">{% trans "Sachgebiet" %}:</span>
            <span id='main-topic-ger'>...</span>
            <span id='main-topic-pl' class='flag-icon flag-icon-pl' data-translate-flag='true' data-toggle='tooltip' data-placement='top'></span><br>
            <span class="font-weight-bold">{% trans "Untersachgebiet" %}:</span>
            <span id='under-topic-ger'>...</span>
            <span id='under-topic-pl' class='flag-icon flag-icon-pl' data-translate-flag='true' data-toggle='tooltip' data-placement='top'></span>
        </p>
    </div>
    <div class='account-bg m-2 p-2'>
        <div class='text-center'>
            <p>{% trans "Frage" %}:
                <span id='question-id'>
                    ...
                </span>
            </p>
            <p>
                <span id='question-ger'>
                    ...
                </span>
                <span id='question-pl' data-translate-flag='true' data-toggle="tooltip" data-placement="top">
                    <span class='flag-icon flag-icon-pl'></span>
                </span>
            </p>
        </div>
        <div class='container'>
            <div class='form-check'>
                <div class='col-6 offset-3'>
                    <input class='form-check-input' type='radio' name='answers' id='answer-A'>
                    <label class='form-check-label' for='answer-A' id='answer-A-label'>
                        ...
                    </label>
                    <span id='answer-A-pl' class='flag-icon flag-icon-pl' data-translate-flag='true' data-toggle='tooltip' data-placement='top'></span>
                </div>
            </div>
            <div class='form-check'>
                <div class='col-6 offset-3'>
                    <input class='form-check-input' type='radio' name='answers' id='answer-B'>
                    <label class='form-check-label' for='answer-B' id='answer-B-label'>
                        ...
                    </label>
                    <span id='answer-B-pl' class='flag-icon flag-icon-pl' data-translate-flag='true' data-toggle='tooltip' data-placement='top'></span>
                </div>
            </div>
            <div class='form-check'>
                <div class='col-6 offset-3'>
                    <input class='form-check-input' type='radio' name='answers' id='answer-C'>
                    <label class='form-check-label' for='answer-C' id='answer-C-label'>
                        ...
                    </label>
                    <span id='answer-C-pl' class='flag-icon flag-icon-pl' data-translate-flag='true' data-toggle='tooltip' data-placement='top'></span>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id='check-question-modal' tabindex="-1" role="dialog" aria-labelledby="chec-question-label" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id='check-question-label'>{% trans "Ergebnis" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p id='check-result-modal-body'></p>
                    <p id='correct-answer-modal-body'></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="far fa-copy"></i> {% trans "nochmal versuchen" %}</button>
                    <button id='modal-correct-answer-btn' type="button" class="btn btn-secondary"><i class="far fa-check-circle"></i> {% trans "richtige Antwort" %}</button>
                    <button id='modal-new-question-btn' type="button" class="btn btn-secondary" data-dismiss="modal"><i class="far fa-file"></i> {% trans "neue Frage" %}</button>
                </div>
             </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>

        makeQuestionsData = () => {
            const questions = [];
            let nextQuestion;
            let answersGer;

            {% for question in all_questions %}
                nextQuestion = {};
                nextQuestion.questionId = parseInt('{{ question.question_id }}');
                nextQuestion.mainTopicGer = '{{ question.main_topic_ger }}';
                nextQuestion.mainTopicPl = '{{ question.main_topic_pl }}';
                nextQuestion.underTopicGer = '{{ question.under_topic_ger }}';
                nextQuestion.underTopicPl = '{{ question.under_topic_pl }}';
                nextQuestion.questionGer = '{{ question.question_ger }}';
                nextQuestion.questionPl = '{{ question.question_pl }}';
                answersGer = [];
                answersGer.push('{{ question.answer_a_ger }}');
                answersGer.push('{{ question.answer_b_ger }}');
                answersGer.push('{{ question.answer_c_ger }}');
                nextQuestion.answersGer = answersGer;
                answersPl = [];
                answersPl.push('{{ question.answer_a_pl }}');
                answersPl.push('{{ question.answer_b_pl }}');
                answersPl.push('{{ question.answer_c_pl }}');
                nextQuestion.answersPl = answersPl;
                nextQuestion.correctAnswerGer = '{{ question.correct_answer_ger }}';
                questions.push(nextQuestion);
            {% endfor %}

            return questions;
        }

        uncheckedRadios = () => {
            document.querySelector('#answer-A').checked = false;
            document.querySelector('#answer-B').checked = false;
            document.querySelector('#answer-C').checked = false;
        }

        prepareQuestion = (question) => {
            document.querySelector('#question-id').textContent = question.questionId;
            document.querySelector('#main-topic-ger').textContent = question.mainTopicGer + ' ';

            $(function(){
                $('#main-topic-pl').tooltip('dispose').tooltip({title:question.mainTopicPl}).tooltip();
            })

            document.querySelector('#under-topic-ger').textContent = question.underTopicGer + ' ';

            $(function(){
                $('#under-topic-pl').tooltip('dispose').tooltip({title:question.underTopicPl}).tooltip();
            })

            document.querySelector('#question-ger').textContent = question.questionGer;

            $(function(){
                $('#question-pl').tooltip('dispose').tooltip({title:question.questionPl}).tooltip();
            })

            const shuffledAnswerIndexs = shuffleQuestionsAnswer(); // returns array 0,1,2 in random order
            document.querySelector('#answer-A-label').textContent = question.answersGer[shuffledAnswerIndexs[0]];
            document.querySelector('#answer-B-label').textContent = question.answersGer[shuffledAnswerIndexs[1]];
            document.querySelector('#answer-C-label').textContent = question.answersGer[shuffledAnswerIndexs[2]];

            document.querySelector('#answer-A').value = question.answersGer[shuffledAnswerIndexs[0]];

            $(function(){
                $('#answer-A-pl').tooltip('dispose').tooltip({title:question.answersPl[shuffledAnswerIndexs[0]]}).tooltip();
            })

            document.querySelector('#answer-B').value = question.answersGer[shuffledAnswerIndexs[1]];

            $(function(){
                $('#answer-B-pl').tooltip('dispose').tooltip({title:question.answersPl[shuffledAnswerIndexs[1]]}).tooltip();
            })

            document.querySelector('#answer-C').value = question.answersGer[shuffledAnswerIndexs[2]];

            $(function(){
                $('#answer-C-pl').tooltip('dispose').tooltip({title:question.answersPl[shuffledAnswerIndexs[2]]}).tooltip();
            })
            
            uncheckedRadios();
        }

        drawQuestion = () => {
            const randomNumber = Math.floor(Math.random() * 600) + 1;
            const questions = makeQuestionsData();
            const simpleQuestion = questions[randomNumber];
            prepareQuestion(simpleQuestion);
        }

        shuffleQuestionsAnswer = () => {
            const array = [0,1,2];
            array.sort(()=>Math.random()-0.5);
            return array;
        }

        getUserAnswer = () => {
            let userAnswer;
            try {
                userAnswer = document.querySelector('input[name="answers"]:checked').value;
            }
            catch (err){
                userAnswer = 'no answer';
            }
            return userAnswer;
        }

        checkQuestion = () => {
            const userAnswer = getUserAnswer();
            const questionId = parseInt(document.querySelector('#question-id').textContent);
            const allQuestions = makeQuestionsData();
            const correctAnswer = allQuestions[questionId-1].correctAnswerGer; // index in array from 0, questions from 1
            const modalBody = document.querySelector('#check-result-modal-body');
            userAnswer == correctAnswer ? modalBody.textContent= 'correct' : modalBody.textContent = 'false';
            $("#check-question-modal").modal()
        }

        const drawNewQuestionButton = document.querySelector('#draw-new-question-btn');
        drawNewQuestionButton.addEventListener('click',drawQuestion);

        const checkQuestionButton = document.querySelector('#check-question-btn');
        checkQuestionButton.addEventListener('click',checkQuestion);

        showHideTranslate = () => {

            const allTranslateFlag = document.querySelectorAll('[data-translate-flag="true"]');
            const selectedLanguage = document.querySelector('#language-select');

            if(selectedLanguage.value=='de'){
                for(let i=0;i<allTranslateFlag.length;i++){
                    allTranslateFlag[i].style.display='none';
                }
            } else {
                for(let i=0;i<allTranslateFlag.length;i++){
                    allTranslateFlag[i].style.display='inline-block'; // spans
                }
                allTranslateFlag[0].style.display='block'; // paragraph
            };
        }

        const modalNewQuestionBtn = document.querySelector('#modal-new-question-btn');
        modalNewQuestionBtn.addEventListener('click',drawQuestion);

        showCorrectAnswer = () => {
            const correctAnswerInModal = document.querySelector('#correct-answer-modal-body');
            correctAnswerInModal.textContent = 'something';
        }

        const modalCorrectAnswerBtn = document.querySelector('#modal-correct-answer-btn');
        modalCorrectAnswerBtn.addEventListener('click',showCorrectAnswer);

        drawQuestion();
        showHideTranslate();

    </script>
{% endblock %}