fisch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('',include('question.urls', namespace='question')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
]

question/urls.py
from django.urls import path
from . import views

app_name = 'question'

urlpatterns = [
    path('simple_question',views.simple_question,name='simple_question'),
    path('simple_test',views.simple_test,name='simple_test'),
    path('fischerschein_info',views.fischerschein_info,name='fischerschein_info'),
    path('FAQ',views.FAQ,name='FAQ'),
    path('project_info',views.project_info,name='project_info'),
    path('',views.main_page,name='main_page'),
]

templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html translate="no">
<head>
    <meta charset='utf-8'>
    <meta name="google" content="notranslate">
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Fischerschein - Quiz</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' integrity='sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh' crossorigin='anonymous'>
    <link rel='stylesheet' type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.3.1/css/flag-icon.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel='stylesheet' type='text/css' href="{% static 'css/main.css' %}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-163432324-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-163432324-1');
    </script>

</head>
<body class="notranslate">
    <nav class='navbar navbar-expand-lg navbar-light bg-light'>
        <a class='navbar-brand' href='{% url "question:main_page" %}'><i class="fas fa-home"></i></a>
        <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNavAltMarkup' aria-controls='navbarNavAltMarkup' aria-expanded='false' aria-label='Toggle navigation'>
            <span class='navbar-toggler-icon'></span>
        </button>
        <div class='collapse navbar-collapse' id='navbarNavAltMarkup'>
            <ul class='navbar-nav mr-auto'>
                <li class='nav-item active'>
                    <a class='nav-item nav-link' href='{% url "question:simple_question" %}'><i class="far fa-comment"></i> {% trans "einzelne Frage" %}</a>
                </li>
                <li class="nav-item">
                    <a class='nav-item nav-link' href='{% url "question:simple_test" %}'><i class="far fa-comments"></i> {% trans "vollständiger Test" %}</a>
                </li>
                <li class="nav-item">
                    <a class='nav-item nav-link' href='{% url "question:fischerschein_info" %}'><i class="fas fa-info"></i> {% trans "über Fischereischein" %}</a>
                </li>
                <li class="nav-item">
                    <a class='nav-item nav-link' href='{% url "question:FAQ" %}'><i class="far fa-clipboard"></i> FAQ</a>
                </li>
                <li class="nav-item">
                    <a class='nav-item nav-link' href='{% url "question:project_info" %}'><i class="fas fa-user-tie"></i> {% trans "über das Projekt und mich" %}</a>
                </li>
            </ul>
            <div class="form-inline my-2 my-lg-0">
                language:
                <form id='change-lang-form' action='{% url "set_language" %}' method='post'>
                    {% csrf_token %}
                    <input type='hidden' name='text' value='{{ redirect_to }}'>
                    <select name='language' id='language-select' data-show-content='true' class='form-control selectpicker'>
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% get_current_language as LANGUAGE_CODE %}
                        {% for language in languages %}
                            <option id='language-{{ language.code }}' data-content="<span class='flag-icon flag-icon-{{ language.code }}'>" value='{{ language.code }}' {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                            </option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
    </nav>
    <div class='hero-image'>
        <div class='hero-text'>
            <h1>{% trans "Machen Sie sich bereit für die Fischerscheinprüfung in Brandenburg" %}</h1>
            <p>
                <span>{% trans "schnell, einfach und kostenlos" %}</span>
            </p>
        </div>
    </div>
    <div id='content'>
        {% block content %}
        {% endblock %}
    </div>

    <script src='https://code.jquery.com/jquery-3.4.1.slim.min.js' integrity='sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n' crossorigin='anonymous'></script>
    <script src='https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js' integrity='sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo' crossorigin='anonymous'></script>
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js' integrity='sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6' crossorigin='anonymous'></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

    <script>
        $( document ).ready(function() {
            $('.selectpicker').selectpicker();

            const language = document.querySelector('#language-select');

            showHideTranslate = () => {

                const allTranslateFlag = document.querySelectorAll('[data-translate-flag="true"]');
                const selectedLanguage = document.querySelector('#language-select');

                if(selectedLanguage.value=='de'){
                    for(let i=0;i<allTranslateFlag.length;i++){
                        allTranslateFlag[i].style.display='none';
                    }
                } else {
                    for(let i=0;i<allTranslateFlag.length;i++){
                        allTranslateFlag[i].style.display='inline-block'; // spans
                    }
                    allTranslateFlag[0].style.display='block'; // paragraph
                };
            }

            changeLanguage = () => {

                const languageSelect = document.querySelector('#language-select');

                const languageForm = document.querySelector('#change-lang-form');

                const languageDE = document.querySelector("#language-de");
                const languagePL = document.querySelector("#language-pl");
                const innerCountryFlag = document.querySelector(".filter-option-inner-inner");

                if(languageSelect.value==='de'){
                    language.selectedIndex = 0;
                    let span = document.createElement('span');
                    innerCountryFlag.firstChild.remove();
                    span.classList.add('flag-icon', 'flag-icon-de');
                    innerCountryFlag.appendChild(span);
                }
                if(languageSelect.value==='pl'){
                    language.selectedIndex = 1;
                    let span = document.createElement('span');
                    innerCountryFlag.firstChild.remove();
                    span.classList.add('flag-icon', 'flag-icon-pl');
                    innerCountryFlag.appendChild(span);
                }

                languageForm.submit();
                showHideTranslate();
            }

            language.addEventListener('change',changeLanguage);

        });

    </script>

    {% block javascript %}
    {% endblock %}
</body>
</html>